apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aService.serviceName }}-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.aService.appName }}-{{ .Release.Name }}
  ports:
      - protocol: TCP
        port: {{ .Values.aService.port }}
        targetPort: {{ .Values.aService.targetPort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.aService.appName }}-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.aService.appName }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.aService.appName }}-{{ .Release.Name }}
    spec:
      containers:
          - name: webserver
            image: {{ .Values.aService.image }}
            imagePullPolicy: {{ .Values.pullPolicy }}
            env:
              - name: WEB_PORT
                value: {{ .Values.aService.targetPort | quote }}
            ports:
              - containerPort: {{ .Values.aService.targetPort }}
            resources:
              requests:
                memory: {{ .Values.aService.memoryRequests }}
                cpu: {{ .Values.aService.cpuRequests }}
              limits:
                memory: {{ .Values.aService.memoryLimits }}
                cpu: {{ .Values.aService.cpuLimits }}
            livenessProbe:
              httpGet:
                path: /health
                port: {{ .Values.aService.targetPort }}
              initialDelaySeconds: {{ .Values.aService.livenessDelay }}
              periodSeconds: {{ .Values.aService.livenessPeriod }}


