apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dvService.serviceName }}-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.dvService.appName }}-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.dvService.port }}
      targetPort: {{ .Values.dvService.targetPort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dvService.appName }}-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.dvService.appName }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dvService.appName }}-{{ .Release.Name }}
    spec:
      containers:
        - name: webserver
          image: {{ .Values.dvService.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: WEB_PORT
              value: {{ .Values.dvService.targetPort | quote }}
          ports:
            - containerPort: {{ .Values.dvService.targetPort }}
          resources:
            requests:
              memory: {{ .Values.dvService.memoryRequests }}
              cpu: {{ .Values.dvService.cpuRequests }}
            limits:
              memory: {{ .Values.dvService.memoryLimits }}
              cpu: {{ .Values.dvService.cpuLimits }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.dvService.targetPort }}
            initialDelaySeconds: {{ .Values.dvService.livenessDelay }}
            periodSeconds: {{ .Values.dvService.livenessPeriod }}


